### ISSUE TITLE
Unable to build; index.css missing

### ISSUE THREAD

**Issue by Xiard** [ninjawithkillmoon/gloomhaven-companion#2]
I’m working on building the app. Like I said, I haven’t worked in React before, but so far it looks pretty straightforward from what I can tell. Here’s what I’ve done:
 
* Installed git & the GitHub desktop.
* Installed NodeJS
* Installed various NodeJS modules from the NodeJS command prompt (including running npm install in my F:\Projects\gloomhaven-thearcanelibrary folder.
* Installed Webstorm and setup Git, GitHub and NodeJS.
 
Now I’m trying to build the app and run it on http://localhost:3000. When I run npm start, I am getting errors. The meat of the output appears to be here:
 
"C:\Program Files\JetBrains\WebStorm 2017.1.3\bin\runnerw.exe" "E:\Program Files\nodejs\node.exe" "E:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" run start --scripts-prepend-node-path=auto
 
> gloomhaven-companion@0.1.0 start F:\Projects\gloomhaven-thearcanelibrary
> npm-run-all -p watch-css start-js
 
 
> gloomhaven-companion@0.1.0 start-js F:\Projects\gloomhaven-thearcanelibrary
> react-scripts start
 
 
> gloomhaven-companion@0.1.0 watch-css F:\Projects\gloomhaven-thearcanelibrary
> npm run build-css && node-sass src/ -o src/ --watch --recursive
 
 
> gloomhaven-companion@0.1.0 build-css F:\Projects\gloomhaven-thearcanelibrary
> node-sass src/ -o src/
 
Starting the development server...
 
Rendering Complete, saving .css file...
Wrote CSS to F:\Projects\gloomhaven-thearcanelibrary\src\App.css
Rendering Complete, saving .css file...
Wrote CSS to F:\Projects\gloomhaven-thearcanelibrary\src\stylesheets\main.css
Wrote 2 CSS files to F:\Projects\gloomhaven-thearcanelibrary\src\
Failed to compile.
 
Error in ./src/index.js
Module not found: ./index.css in F:\Projects\gloomhaven-thearcanelibrary\src
 
I don’t see index.css in the repo, and it is definitely referenced in index.js. It appears that react builds .css files from .scss files (like App.scss), but there is no index.scss file that would be used to create index.css.
 
Do you think I’m missing a file, or is there some other key setup factor I missed?

**Comment by ninjawithkillmoon** [comment]
Try putting an index.css file in the same folder as the App.scss file with the following contents: 

body { margin: 0; padding: 0; font-family: sans-serif; }

Possibly I've missed including it in version control, possibly it should be removed and replaced by App.css. Can't really check until I get internet access at home again.

**Comment by Xiard** [comment]
Thanks.  That got me further, but there are other compile errors.  No rush, obviously.  Just tinkering.  From what I can tell, it does sound like there might be some items missing from version control.

Good luck with the move.

**Compile Errors**

Error in ./src/components/Header.js
Module not found: 'react-file-reader-input' in F:\Projects\gloomhaven-thearcanelibrary\src\components

 @ ./src/components/Header.js 26:28-62

Error in ./src/dispatcher/AppDispatcher.js
Module not found: 'flux' in F:\Projects\gloomhaven-thearcanelibrary\src\dispatcher

 @ ./src/dispatcher/AppDispatcher.js 7:12-27

Error in ./src/constants/GameConstants.js
Module not found: 'keymirror' in F:\Projects\gloomhaven-thearcanelibrary\src\constants

 @ ./src/constants/GameConstants.js 7:17-37

Error in ./src/constants/ErrorConstants.js
Module not found: 'keymirror' in F:\Projects\gloomhaven-thearcanelibrary\src\constants

 @ ./src/constants/ErrorConstants.js 7:17-37

Compiling...
Failed to compile.

Error in ./src/components/Header.js
Module not found: 'react-file-reader-input' in F:\Projects\gloomhaven-thearcanelibrary\src\components

 @ ./src/components/Header.js 26:28-62

Error in ./src/dispatcher/AppDispatcher.js
Module not found: 'flux' in F:\Projects\gloomhaven-thearcanelibrary\src\dispatcher

 @ ./src/dispatcher/AppDispatcher.js 7:12-27

Error in ./src/constants/GameConstants.js
Module not found: 'keymirror' in F:\Projects\gloomhaven-thearcanelibrary\src\constants

 @ ./src/constants/GameConstants.js 7:17-37

Error in ./src/constants/ErrorConstants.js
Module not found: 'keymirror' in F:\Projects\gloomhaven-thearcanelibrary\src\constants

 @ ./src/constants/ErrorConstants.js 7:17-37

**Comment by ninjawithkillmoon** [comment]
Some of those look solvable just by installing the correct modules... but I'm going to need to check out the project from scratch and see what I can do. I'm not going to do that at work, so I'll do it when my useless ISP connects my internet. Probably in the next couple of days.

I've not heavily used the node.js environment before, so I'm also learning how to set all this up. It really should be setup to work after an "npm install".

**Comment by Xiard** [comment]
Ah!  Didn't realize those were installable modules.  I am up and running now.  Anything you'd like me to look at?  The Monster Health page, perhaps?

**Comment by ninjawithkillmoon** [comment]
The monster health page might actually be working (just a bit untested) apart from one small feature: ability to select the number of players in a scenario (which then flows on to boss health). Feel free to improve it though - even I don't use that one at the moment, it was experimental.

A few people seem to be waiting for a characters page - you'd make people happy if you built one of those.

The sanctuary donation tracker was also next on my list.

But really... feel free to build whatever you like and will use :)

**Comment by ninjawithkillmoon** [comment]
I've added issues here for the items I know about that have been requested or are known bugs. Feel free to add some more.

I'm closing this issue for now as it seems to be resolved.

Thanks for the assistance once again.
