### ISSUE TITLE
Dropbox save/load is broken

### ISSUE THREAD

**Issue by ssabo** [ninjawithkillmoon/gloomhaven-companion#24]
I am importing my older file from local system, saving to dropbox, refreshing (ctrl + shift + r) and loading. Loading is giving the following error:

```
Error: missing data
    at http://thearcane.li/static/js/main.36bd6b1d.js:13:19638
    at <anonymous>
```

Local Save File - [gloomhaven_save_20170709_1007.txt](https://github.com/ninjawithkillmoon/gloomhaven-thearcanelibrary/files/1137677/gloomhaven_save_20170709_1007.txt)
Dropbox save file - [gloomhaven_save_20170710_2040.txt](https://github.com/ninjawithkillmoon/gloomhaven-thearcanelibrary/files/1137678/gloomhaven_save_20170710_2040.txt)

**Comment by ssabo** [comment]
I just tried downloading the save file from dropbox manually and importing. This appeared to work correctly.

**Comment by ninjawithkillmoon** [comment]
User on BGG having similar issue: https://boardgamegeek.com/article/26337319#26337319

**Comment by ninjawithkillmoon** [comment]
Issue seems to be with party notes being empty.

**Comment by ninjawithkillmoon** [comment]
DropboxChooser.js:

          // quick check that the text content is actually a save game
          if (data.name && data.partyNotes) {
            // load the game into the browser
            GameActions.loadGame(data);
          }
          else {
            // show an error message indicating that this is not the content that we expected
            throw new Error("missing data");
          }

needs to just change into this:

            // load the game into the browser
            GameActions.loadGame(data);

thus removing this check entirely. I can't fix until later today.

**Comment by ssabo** [comment]
Submitted https://github.com/ninjawithkillmoon/gloomhaven-thearcanelibrary/pull/25 per your recommendation.

**Comment by ninjawithkillmoon** [comment]
This is now deployed and looks to be working for me. Can you confirm? (if it still doesn't work, just change the query string to something like this http://thearcane.li/?randomquerystringbollocks to make sure you're running the latest version - sometimes GitHub caches aggressively).

**Comment by ninjawithkillmoon** [comment]
Closing, presumed working now. Thanks for providing the files - they helped find the issue.
