### ISSUE TITLE
Monster Health Tracker - Number of Characters Selector

### ISSUE THREAD

**Issue by ninjawithkillmoon** [ninjawithkillmoon/gloomhaven-companion#4]
Currently hard coded to 4 characters, this affects boss health numbers that are dependent on number of characters.

Should look the same as the scenario level selector.

**Comment by Xiard** [comment]
Sounds pretty simply for a first project.  I'll claim this one.

**Comment by Xiard** [comment]
Changes made and merged ("feature/4" branch).
