### ISSUE TITLE
Save to dropbox no longer working?

### ISSUE THREAD

**Issue by REBELinBLUE** [ninjawithkillmoon/gloomhaven-companion#50]
I can load my campaign but if I try to save it nothing happens, eventually I get a dialog saying

"Failed to fetch"

If I look int the network tab it seems to be making a request to "https://api.myjson.com/bins" which doesn't resolve

**Comment by ninjawithkillmoon** [comment]
Yup, apologies, it looks like the external service that I have used to assist in the process of saving to Dropbox is no longer running. It seems to have been shut down.

I am no longer doing updates or new development for The Arcane Library, so I guess this means no more Dropbox saving.

If you or anybody else reading this need any help working with the import/export for local files just let me know (although I am aware that this might not work on some devices, leaving people out of luck).

**Comment by REBELinBLUE** [comment]
Ah fair enough I hadn't realized it was part of the process, I thought it had maybe accidentally been published with a "mock" URL as I'd never heard of myjson.com before and it sounded fake... I am just using the files locally
